[build]
command = "npm run build:client"
functions = "netlify/functions"
publish = "dist/spa"


[functions]
node_bundler = "esbuild"

[dev]
targetPort = 8080

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
